# m2cell configuration file.

# Setting for logging
Log:
  fileName: "logs/m2cellLog.log"
  fileSizeMB: 10
  maxFiles: 11

# Control server details.
# host is only used by client applications
# Possible port values are 55555 (old) or 50000 (new).
ControlServer:
  host: "127.0.0.1"
  port: 50000
  threads: 3

# Telemetry server details.
# host is only used by client applications
# Possible port values are 50001
TelemetryServer:
  host: "127.0.0.1"
  port: 50001
  threads: 3
