# Unit Test configuration with missing required element.

# Acceptable values for the control server.
ControlServer:
  host: "127.0.0.1"
#  port: 12678   - Missing port should trigger an exception.
  threads: 1

# Acceptable values for the telemetry server.
TelemetryServer:
  host: "127.0.0.1"
  port: 12679
  threads: 3

# Entries made up for unit testing only.
testconstant:
  pi: 3.14159265
