# Normal Unit Test configuration

# Acceptable values for log file setup
Log:
  fileName: "logs/testLog.log"
  fileSizeMB: 10
  maxFiles: 11

# Acceptable values for the control server.
ControlServer:
  host: "127.0.0.1"
  port: 12678
  threads: 1

# Acceptable values for the telemetry server.
TelemetryServer:
  host: "127.0.0.1"
  port: 12679
  threads: 3

# Entries made up for unit testing only.
testconstant:
  pi: 3.14159265

# DaqOutMock entries for testing, optional Config elements.
ILC_Motor_Current_test:
  link: "ILC_Motor_Current"
  scale: 2.0

ILC_Motor_Current:
  scale: 2.0

ILC_Motor_Voltage_test:
  link: "ILC_Motor_Voltage"
  scale: 1.0

ILC_Comm_Current_test:
  link: "ILC_Comm_Current"
  scale: 1.0

ILC_Comm_Voltage_test:
  link: "ILC_Comm_Voltage"
  scale: 1.0

# DaqBoolOutMock entries for testing, optional Config elements.
ILC_Motor_Power_On_out:
  linkBoolIn: "ILC_Motor_Power_On_in"
  linkCurrentOut: "ILC_Motor_Current_test"
  linkCurrentOutVal: 0.5
  linkVoltageOut: "ILC_Motor_Voltage_test"
  linkVoltageOutVal: 8.0

ILC_Comm_Power_On_out:
  linkBoolIn: "ILC_Comm_Power_On_in"
  linkCurrentOut: "ILC_Comm_Current_test"
  linkCurrentOutVal: 0.1
  linkVoltageOut: "ILC_Comm_Voltage_test"
  linkVoltageOutVal: 12.0

cRIO_Interlock_Enable_out:
  linkBoolIn: "cRIO_Interlock_Enable_in"

# Global constants, used in multiple VI's.
# These are used when a value for the entry could not be
# found in a more specific section.
Globals:
  # weight of the seconrary mirror in Newtons
  constMirrorWeightN: 15140

# Constants for the TangentLoadCellFaultDetector VI.
# All of them are in Newtons.
TangentLoadCellFaultDetection:
  constTanWeightErrorN: 2000
  constLoadBearingErrorN: 1000
  constNetMomentErrorN: 1000
  constNotLoadBearingErrorN: 2500
